<script setup lang="ts">
const imageModules = import.meta.glob('../assets/images/home_slideshow/*', { eager: true, import: 'default' })
const images = Object.values(imageModules) as string[]

// Load optimized mapping generated by scripts/image-gen.cjs
import optimized from '~/assets/optimized-images.json'

const currentImageIndex = ref(0)

const slides = images.map((img) => {
  const key = img.split('/').pop() as string
  const mapping = optimized[key]
  return {
    original: img,
    mapping
  }
})

onMounted(() => {
  if (slides.length > 0) {
    setInterval(() => {
      currentImageIndex.value = (currentImageIndex.value + 1) % slides.length
    }, 5000)
  }
})
</script>

<template>
  <div class="absolute inset-0 z-0 overflow-hidden bg-background">
    <!-- Slideshow Images -->
    <transition-group name="fade" tag="div" class="absolute inset-0 h-full w-full">
      <div 
        v-for="(slide, index) in slides" 
        :key="slide.original"
        v-show="currentImageIndex === index"
        class="absolute inset-0"
      >
        <picture v-if="slide.mapping">
          <source type="image/avif" :srcset="slide.mapping.avif" sizes="100vw" />
          <source type="image/webp" :srcset="slide.mapping.webp" sizes="100vw" />
          <img :src="slide.mapping.fallback" alt="Atmospheric Background" class="h-full w-full object-cover opacity-40 transition-transform duration-[10000ms] ease-linear transform scale-100 animate-ken-burns" :loading="currentImageIndex === index ? 'eager' : 'lazy'" :fetchpriority="currentImageIndex === index ? 'high' : 'auto'" decoding="async"/>
        </picture>
        <img v-else :src="slide.original" alt="Atmospheric Background" class="h-full w-full object-cover opacity-40 transition-transform duration-[10000ms] ease-linear transform scale-100 animate-ken-burns" :loading="currentImageIndex === index ? 'eager' : 'lazy'" :fetchpriority="currentImageIndex === index ? 'high' : 'auto'" decoding="async"/>
      </div> 
    </transition-group>

    <!-- Overlay Gradient -->
    <div class="absolute inset-0 bg-gradient-to-t from-background via-background/60 to-transparent"></div>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 1.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

@keyframes ken-burns {
    0% {
        transform: scale(1);
    }
    100% {
        transform: scale(1.1);
    }
}

.animate-ken-burns {
    animation: ken-burns 10s ease-out forwards;
}
</style>
