/**
 * Image Optimization Composable
 * 
 * Looks up optimized image variants (AVIF/WebP) from the mapping file
 * generated by `npm run gen:images`.
 * 
 * Usage:
 *   const mapping = resolveOptimizedImage('/images/photo.jpg')
 *   // Returns: { avif: '...srcset...', webp: '...srcset...', fallback: '...' }
 */
import optimized from '~/assets/optimized-images.json'

export type ImageMapping = {
  avif: string
  webp: string
  fallback: string
}

export function resolveOptimizedImage(url?: string | null): ImageMapping | null {
  if (!url) return null
  
  // Extract filename from path (e.g., '/images/photo.jpg' → 'photo.jpg')
  const key = url.split('/').pop() || ''
  return (optimized as Record<string, ImageMapping>)[key] || null
}
