/**
 * Dynamic Page Colors Composable
 * 
 * Applies a unique accent color to each project page based on
 * the dominant color extracted from its hero image.
 * 
 * Color data is pre-generated by `npm run gen:images` using node-vibrant
 * and stored in assets/image-colors.json.
 * 
 * Usage:
 *   const { applyColors, resetColors } = usePageColors()
 *   onMounted(() => applyColors('/images/hero.jpg'))
 */
import colorData from '~/assets/image-colors.json'

export function usePageColors() {
  const applyColors = (imagePath: string) => {
    if (!imagePath || typeof document === 'undefined') return

    // Extract filename without extension from path (e.g., '/images/hero.jpg' -> 'hero')
    const filename = imagePath.split('/').pop()?.replace(/\.[^/.]+$/, '') || ''
    const colors = colorData[filename as keyof typeof colorData]

    if (colors) {
      // Set CSS custom property used by Tailwind's 'primary' color
      const hslStr = `${colors.hsl.h} ${colors.hsl.s}% ${colors.hsl.l}%`
      document.documentElement.style.setProperty('--color-primary', hslStr)
    }
  }

  const resetColors = () => {
    if (typeof document === 'undefined') return
    // Reset to default cyan
    document.documentElement.style.setProperty('--color-primary', '186 100% 50%')
  }

  return { applyColors, resetColors }
}
